# Yapılandırma dosyaları // Configuration files
server-code: "" # Verification Code // Doğrulama Kodu
players: [] # Player Names:IP Address // Oyuncu İsimleri:Ip Adresleri
settings:
  ip-check: true # IP Control () // IP kontrolü (Açık olması önerilir.)

# Çeviri Dosyaları // Translate Files
language: tr