name: codeWhitelist
version: 1.3
main: net.saganetwork.codeWhitelist.Main
description: Oyuncular için doğrulama kodu ve whitelist sistemi.
author: Saganetwork
commands:
  kod:
    description: Code verification system.
    usage: /kod <kod>
    aliases: ["code"]