name: codeWhitelist
version: 1.6
api-version: '1.20'
main: net.saganetwork.codeWhitelist.Main
description: A plugin for Code Whitelist System.
author: Saganetwork
commands:
  kod:
    description: Code verification system.
    usage: /kod <kod>
    aliases:
      - code